version: '3'

services:
  db:
    build: ./docker/postgresql
    container_name: picup-db
    environment:
      POSTGRES_DB: picup
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      TZ: Asia/Tokyo
    ports:
      - 5432:5432

  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    container_name: picup-app
    # command: bundle exec unicorn -p 3000 -c config/unicorn.rb
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    environment:
      RAILS_ENV: development
      TZ: Asia/Tokyo
    depends_on:
      - db

  # web:
  #   build: ./docker/nginx
  #   container_name: picup-web
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./public:/var/www/public
  #     - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #   environment:
  #     TZ: Asia/Tokyo
  #   links:
  #     - app
