default: &default
  adapter: postgresql
  encoding: unicode
  database: picup
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: db
  username: root
  password: root
  pool: 5

test:
  <<: *default
  username: root
  password: root

production:
  <<: *default
